### ISSUE TITLE
panics in debug build on integer underflow

### ISSUE THREAD

**Issue by gmaxwell** [i7i/asmap-rs#25]
[gmaxwell@argonaut asmap-rs]$ time ./target/debug/asmap-rs find-bottleneck --dir dump/
Reading in and parsing `dump/rrc00-latest-bview.gz`
Skipping unsupported MRT record from TABLE_DUMP_V2.
Reading in and parsing `dump/rrc01-latest-bview.gz`
Skipping unsupported MRT record from TABLE_DUMP_V2.
Reading in and parsing `dump/rrc02-latest-bview.gz`
Skipping unsupported MRT record from TABLE_DUMP_V2.
thread 'main' panicked at 'attempt to subtract with overflow', src/as_path_parser.rs:96:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

real	157m53.960s
user	157m53.079s
sys	0m0.490s

**Comment by rrybarczyk** [comment]
Just merged a fix to print a warning when this happens rather than panic in #26 . Lmk if there are any more issues.
